#ifndef ERRORS_H
#define ERRORS_H
#define COMPILATION_FAILED 10
#define LINKING_FAILED 20
#define EVENTHANDLER_ALREADY_EXISTS 30
#define RENDERER_ALREADY_EXISTS 40
#define GLOBAL_SHADER_LOADING_FAILED 50
#endif //ERRORS_H